/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_management_system;

/**
 *
 * @author PC
 */
public class IssueBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public IssueBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        materialShadowCircle1 = new efectos.MaterialShadowCircle();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Username11 = new javax.swing.JLabel();
        Username10 = new javax.swing.JLabel();
        ContactNumberjCTextField7 = new app.bolivia.swing.JCTextField();
        Password3 = new javax.swing.JLabel();
        Email3 = new javax.swing.JLabel();
        EmailIcon3 = new javax.swing.JLabel();
        UsernamejCTextField3 = new app.bolivia.swing.JCTextField();
        Username4 = new javax.swing.JLabel();
        ContactNumberIcon3 = new javax.swing.JLabel();
        PasswordIcon3 = new javax.swing.JLabel();
        UsernameIcon3 = new javax.swing.JLabel();
        EmailjCTextField6 = new app.bolivia.swing.JCTextField();
        PasswordjCTextField5 = new app.bolivia.swing.JCTextField();
        ContactNumber3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        Username3 = new javax.swing.JLabel();
        UsernameIcon2 = new javax.swing.JLabel();
        PasswordIcon2 = new javax.swing.JLabel();
        Password2 = new javax.swing.JLabel();
        Email2 = new javax.swing.JLabel();
        EmailIcon2 = new javax.swing.JLabel();
        ContactNumber2 = new javax.swing.JLabel();
        ContactNumberIcon2 = new javax.swing.JLabel();
        UsernamejCTextField2 = new app.bolivia.swing.JCTextField();
        PasswordjCTextField4 = new app.bolivia.swing.JCTextField();
        EmailjCTextField5 = new app.bolivia.swing.JCTextField();
        ContactNumberjCTextField6 = new app.bolivia.swing.JCTextField();
        Username8 = new javax.swing.JLabel();
        Username9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        Username5 = new javax.swing.JLabel();
        UsernameIcon4 = new javax.swing.JLabel();
        PasswordIcon4 = new javax.swing.JLabel();
        Password4 = new javax.swing.JLabel();
        Email4 = new javax.swing.JLabel();
        EmailIcon4 = new javax.swing.JLabel();
        ContactNumber4 = new javax.swing.JLabel();
        ContactNumberIcon4 = new javax.swing.JLabel();
        UsernamejCTextField4 = new app.bolivia.swing.JCTextField();
        ContactNumberjCTextField9 = new app.bolivia.swing.JCTextField();
        ContactNumberjCTextField10 = new app.bolivia.swing.JCTextField();
        UsernamejCTextField5 = new app.bolivia.swing.JCTextField();
        Username6 = new javax.swing.JLabel();
        Username7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(71, 136, 199));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 6, 1080, 50));

        jPanel2.setBackground(new java.awt.Color(71, 136, 199));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(71, 136, 199));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel28.setText("  Home Page");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(15, 15, 15))
        );

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 240, 40));

        jPanel11.setBackground(new java.awt.Color(71, 136, 199));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-books-30 (1).png"))); // NOI18N
        jLabel29.setText("  Manage Books");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(15, 15, 15))
        );

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 40));

        jPanel12.setBackground(new java.awt.Color(71, 136, 199));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-borrow-book-30.png"))); // NOI18N
        jLabel30.setText("  Issue Book");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(15, 15, 15))
        );

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 240, 40));

        jPanel23.setBackground(new java.awt.Color(71, 136, 199));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-students-30.png"))); // NOI18N
        jLabel31.setText("  Manage Students");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(15, 15, 15))
        );

        jPanel2.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, 40));

        jPanel24.setBackground(new java.awt.Color(71, 136, 199));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel32.setText("   Default List");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addGap(15, 15, 15))
        );

        jPanel2.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 240, 40));

        jPanel27.setBackground(new java.awt.Color(71, 136, 199));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-return-book-30.png"))); // NOI18N
        jLabel35.setText("  Return Book");

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel35)
                .addGap(15, 15, 15))
        );

        jPanel2.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, 40));

        jPanel25.setBackground(new java.awt.Color(71, 136, 199));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-course-assign-30.png"))); // NOI18N
        jLabel33.setText("  View Issued Books");

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addGap(15, 15, 15))
        );

        jPanel2.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 240, 40));

        jPanel26.setBackground(new java.awt.Color(71, 136, 199));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-records-30.png"))); // NOI18N
        jLabel34.setText("  View Records");

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addGap(15, 15, 15))
        );

        jPanel2.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, 40));

        jPanel28.setBackground(new java.awt.Color(71, 136, 199));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-logout-30.png"))); // NOI18N
        jLabel36.setText("  Logout");

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel36)
                .addGap(15, 15, 15))
        );

        jPanel2.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 240, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 250, 730));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 2, 2, 2, new java.awt.Color(71, 136, 199)));
        jPanel8.setPreferredSize(new java.awt.Dimension(520, 395));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(71, 136, 199));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-books-50.png"))); // NOI18N

        Username11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Username11.setForeground(new java.awt.Color(71, 136, 199));
        Username11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Username11.setText("Book Details");

        Username10.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Username10.setForeground(new java.awt.Color(71, 136, 199));
        Username10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Username10.setText("|");

        ContactNumberjCTextField7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(71, 136, 199)));
        ContactNumberjCTextField7.setForeground(new java.awt.Color(71, 136, 199));
        ContactNumberjCTextField7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ContactNumberjCTextField7.setPhColor(new java.awt.Color(71, 136, 199));
        ContactNumberjCTextField7.setPlaceholder("Quantity");
        ContactNumberjCTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNumberjCTextField7ActionPerformed(evt);
            }
        });

        Password3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Password3.setForeground(new java.awt.Color(71, 136, 199));
        Password3.setText("Book Name");

        Email3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Email3.setForeground(new java.awt.Color(71, 136, 199));
        Email3.setText("Author");

        EmailIcon3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EmailIcon3.setForeground(new java.awt.Color(71, 136, 199));
        EmailIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-author-40.png"))); // NOI18N

        UsernamejCTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(71, 136, 199)));
        UsernamejCTextField3.setForeground(new java.awt.Color(71, 136, 199));
        UsernamejCTextField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UsernamejCTextField3.setPhColor(new java.awt.Color(71, 136, 199));
        UsernamejCTextField3.setPlaceholder("Book ID");
        UsernamejCTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernamejCTextField3ActionPerformed(evt);
            }
        });

        Username4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Username4.setForeground(new java.awt.Color(71, 136, 199));
        Username4.setText("Book ID");

        ContactNumberIcon3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ContactNumberIcon3.setForeground(new java.awt.Color(71, 136, 199));
        ContactNumberIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-math-book-40.png"))); // NOI18N

        PasswordIcon3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PasswordIcon3.setForeground(new java.awt.Color(71, 136, 199));
        PasswordIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-wordbook-40.png"))); // NOI18N

        UsernameIcon3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        UsernameIcon3.setForeground(new java.awt.Color(71, 136, 199));
        UsernameIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-informatics-book-40.png"))); // NOI18N

        EmailjCTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(71, 136, 199)));
        EmailjCTextField6.setForeground(new java.awt.Color(71, 136, 199));
        EmailjCTextField6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmailjCTextField6.setPhColor(new java.awt.Color(71, 136, 199));
        EmailjCTextField6.setPlaceholder("Author");
        EmailjCTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailjCTextField6ActionPerformed(evt);
            }
        });

        PasswordjCTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(71, 136, 199)));
        PasswordjCTextField5.setForeground(new java.awt.Color(71, 136, 199));
        PasswordjCTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PasswordjCTextField5.setPhColor(new java.awt.Color(71, 136, 199));
        PasswordjCTextField5.setPlaceholder("Book Name");
        PasswordjCTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordjCTextField5ActionPerformed(evt);
            }
        });

        ContactNumber3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ContactNumber3.setForeground(new java.awt.Color(71, 136, 199));
        ContactNumber3.setText("Quantity");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(PasswordIcon3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Password3)
                            .addComponent(PasswordjCTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(EmailIcon3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Email3)
                            .addComponent(EmailjCTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(ContactNumberIcon3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContactNumberjCTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(ContactNumber3)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(UsernameIcon3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernamejCTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Username4)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Username10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Username11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Username11)
                        .addComponent(Username10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Username4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsernameIcon3, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(UsernamejCTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(Password3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordIcon3, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PasswordjCTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Email3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailIcon3, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(EmailjCTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(ContactNumber3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContactNumberIcon3, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ContactNumberjCTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 62, 508, 435));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 2, 2, 2, new java.awt.Color(71, 136, 199)));
        jPanel9.setPreferredSize(new java.awt.Dimension(520, 395));

        Username3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Username3.setForeground(new java.awt.Color(71, 136, 199));
        Username3.setText("Book ID");

        UsernameIcon2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        UsernameIcon2.setForeground(new java.awt.Color(71, 136, 199));
        UsernameIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-informatics-book-40.png"))); // NOI18N

        PasswordIcon2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PasswordIcon2.setForeground(new java.awt.Color(71, 136, 199));
        PasswordIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-wordbook-40.png"))); // NOI18N

        Password2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Password2.setForeground(new java.awt.Color(71, 136, 199));
        Password2.setText("Book Name");

        Email2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Email2.setForeground(new java.awt.Color(71, 136, 199));
        Email2.setText("Author");

        EmailIcon2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EmailIcon2.setForeground(new java.awt.Color(71, 136, 199));
        EmailIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-author-40.png"))); // NOI18N

        ContactNumber2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ContactNumber2.setForeground(new java.awt.Color(71, 136, 199));
        ContactNumber2.setText("Quantity");

        ContactNumberIcon2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ContactNumberIcon2.setForeground(new java.awt.Color(71, 136, 199));
        ContactNumberIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-math-book-40.png"))); // NOI18N

        UsernamejCTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(71, 136, 199)));
        UsernamejCTextField2.setForeground(new java.awt.Color(71, 136, 199));
        UsernamejCTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UsernamejCTextField2.setPhColor(new java.awt.Color(71, 136, 199));
        UsernamejCTextField2.setPlaceholder("Book ID");
        UsernamejCTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernamejCTextField2ActionPerformed(evt);
            }
        });

        PasswordjCTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(71, 136, 199)));
        PasswordjCTextField4.setForeground(new java.awt.Color(71, 136, 199));
        PasswordjCTextField4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PasswordjCTextField4.setPhColor(new java.awt.Color(71, 136, 199));
        PasswordjCTextField4.setPlaceholder("Book Name");
        PasswordjCTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordjCTextField4ActionPerformed(evt);
            }
        });

        EmailjCTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(71, 136, 199)));
        EmailjCTextField5.setForeground(new java.awt.Color(71, 136, 199));
        EmailjCTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmailjCTextField5.setPhColor(new java.awt.Color(71, 136, 199));
        EmailjCTextField5.setPlaceholder("Author");
        EmailjCTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailjCTextField5ActionPerformed(evt);
            }
        });

        ContactNumberjCTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(71, 136, 199)));
        ContactNumberjCTextField6.setForeground(new java.awt.Color(71, 136, 199));
        ContactNumberjCTextField6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ContactNumberjCTextField6.setPhColor(new java.awt.Color(71, 136, 199));
        ContactNumberjCTextField6.setPlaceholder("Quantity");
        ContactNumberjCTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNumberjCTextField6ActionPerformed(evt);
            }
        });

        Username8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Username8.setForeground(new java.awt.Color(71, 136, 199));
        Username8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Username8.setText("Student Details");

        Username9.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Username9.setForeground(new java.awt.Color(71, 136, 199));
        Username9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Username9.setText("|");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(71, 136, 199));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-books-50.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UsernameIcon2)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsernamejCTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(Username9)
                                .addGap(3, 3, 3)
                                .addComponent(Username8))
                            .addComponent(Username3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(ContactNumberIcon2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(ContactNumber2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(ContactNumberjCTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(PasswordIcon2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(Password2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(PasswordjCTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(EmailIcon2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(Email2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(EmailjCTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Username8)
                        .addComponent(Username9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Username3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsernameIcon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(UsernamejCTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(Password2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordIcon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PasswordjCTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Email2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailIcon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(EmailjCTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(ContactNumber2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContactNumberIcon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ContactNumberjCTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 62, 504, 435));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 2, 2, 2, new java.awt.Color(71, 136, 199)));
        jPanel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel13.setPreferredSize(new java.awt.Dimension(520, 395));

        Username5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Username5.setForeground(new java.awt.Color(71, 136, 199));
        Username5.setText("Book ID");

        UsernameIcon4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        UsernameIcon4.setForeground(new java.awt.Color(71, 136, 199));
        UsernameIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-informatics-book-40.png"))); // NOI18N

        PasswordIcon4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PasswordIcon4.setForeground(new java.awt.Color(71, 136, 199));
        PasswordIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-wordbook-40.png"))); // NOI18N

        Password4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Password4.setForeground(new java.awt.Color(71, 136, 199));
        Password4.setText("Book Name");

        Email4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Email4.setForeground(new java.awt.Color(71, 136, 199));
        Email4.setText("Author");

        EmailIcon4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EmailIcon4.setForeground(new java.awt.Color(71, 136, 199));
        EmailIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-author-40.png"))); // NOI18N

        ContactNumber4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ContactNumber4.setForeground(new java.awt.Color(71, 136, 199));
        ContactNumber4.setText("Quantity");

        ContactNumberIcon4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ContactNumberIcon4.setForeground(new java.awt.Color(71, 136, 199));
        ContactNumberIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-math-book-40.png"))); // NOI18N

        UsernamejCTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(71, 136, 199)));
        UsernamejCTextField4.setForeground(new java.awt.Color(71, 136, 199));
        UsernamejCTextField4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UsernamejCTextField4.setPhColor(new java.awt.Color(71, 136, 199));
        UsernamejCTextField4.setPlaceholder("Book ID");
        UsernamejCTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernamejCTextField4ActionPerformed(evt);
            }
        });

        ContactNumberjCTextField9.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(71, 136, 199)));
        ContactNumberjCTextField9.setForeground(new java.awt.Color(71, 136, 199));
        ContactNumberjCTextField9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ContactNumberjCTextField9.setPhColor(new java.awt.Color(71, 136, 199));
        ContactNumberjCTextField9.setPlaceholder("Quantity");
        ContactNumberjCTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNumberjCTextField9ActionPerformed(evt);
            }
        });

        ContactNumberjCTextField10.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(71, 136, 199)));
        ContactNumberjCTextField10.setForeground(new java.awt.Color(71, 136, 199));
        ContactNumberjCTextField10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ContactNumberjCTextField10.setPhColor(new java.awt.Color(71, 136, 199));
        ContactNumberjCTextField10.setPlaceholder("Quantity");
        ContactNumberjCTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNumberjCTextField10ActionPerformed(evt);
            }
        });

        UsernamejCTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(71, 136, 199)));
        UsernamejCTextField5.setForeground(new java.awt.Color(71, 136, 199));
        UsernamejCTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UsernamejCTextField5.setPhColor(new java.awt.Color(71, 136, 199));
        UsernamejCTextField5.setPlaceholder("Book ID");
        UsernamejCTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernamejCTextField5ActionPerformed(evt);
            }
        });

        Username6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Username6.setForeground(new java.awt.Color(71, 136, 199));
        Username6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Username6.setText("Book ID");

        Username7.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Username7.setForeground(new java.awt.Color(71, 136, 199));
        Username7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Username7.setText("|");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(71, 136, 199));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-books-50.png"))); // NOI18N

        jButton15.setBackground(new java.awt.Color(71, 136, 199));
        jButton15.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Confirm");
        jButton15.setBorder(null);
        jButton15.setFocusPainted(false);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Username7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Username6))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(PasswordIcon4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UsernamejCTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(UsernameIcon4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Username5)
                            .addComponent(Password4)
                            .addComponent(UsernamejCTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ContactNumberIcon4)
                    .addComponent(EmailIcon4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Email4)
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ContactNumberjCTextField9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ContactNumberjCTextField10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ContactNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(ContactNumber4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ContactNumberjCTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContactNumberIcon4))
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(Email4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ContactNumberjCTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(EmailIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(Username6))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Username7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Username5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernamejCTextField5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsernameIcon4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(13, 13, 13)
                        .addComponent(Password4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasswordIcon4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UsernamejCTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 503, 1018, 233));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernamejCTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernamejCTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernamejCTextField2ActionPerformed

    private void PasswordjCTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordjCTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordjCTextField4ActionPerformed

    private void EmailjCTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailjCTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailjCTextField5ActionPerformed

    private void ContactNumberjCTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNumberjCTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactNumberjCTextField6ActionPerformed

    private void ContactNumberjCTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNumberjCTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactNumberjCTextField7ActionPerformed

    private void EmailjCTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailjCTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailjCTextField6ActionPerformed

    private void PasswordjCTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordjCTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordjCTextField5ActionPerformed

    private void UsernamejCTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernamejCTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernamejCTextField3ActionPerformed

    private void UsernamejCTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernamejCTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernamejCTextField5ActionPerformed

    private void ContactNumberjCTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNumberjCTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactNumberjCTextField10ActionPerformed

    private void ContactNumberjCTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNumberjCTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactNumberjCTextField9ActionPerformed

    private void UsernamejCTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernamejCTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernamejCTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContactNumber2;
    private javax.swing.JLabel ContactNumber3;
    private javax.swing.JLabel ContactNumber4;
    private javax.swing.JLabel ContactNumberIcon2;
    private javax.swing.JLabel ContactNumberIcon3;
    private javax.swing.JLabel ContactNumberIcon4;
    private app.bolivia.swing.JCTextField ContactNumberjCTextField10;
    private app.bolivia.swing.JCTextField ContactNumberjCTextField6;
    private app.bolivia.swing.JCTextField ContactNumberjCTextField7;
    private app.bolivia.swing.JCTextField ContactNumberjCTextField9;
    private javax.swing.JLabel Email2;
    private javax.swing.JLabel Email3;
    private javax.swing.JLabel Email4;
    private javax.swing.JLabel EmailIcon2;
    private javax.swing.JLabel EmailIcon3;
    private javax.swing.JLabel EmailIcon4;
    private app.bolivia.swing.JCTextField EmailjCTextField5;
    private app.bolivia.swing.JCTextField EmailjCTextField6;
    private javax.swing.JLabel Password2;
    private javax.swing.JLabel Password3;
    private javax.swing.JLabel Password4;
    private javax.swing.JLabel PasswordIcon2;
    private javax.swing.JLabel PasswordIcon3;
    private javax.swing.JLabel PasswordIcon4;
    private app.bolivia.swing.JCTextField PasswordjCTextField4;
    private app.bolivia.swing.JCTextField PasswordjCTextField5;
    private javax.swing.JLabel Username10;
    private javax.swing.JLabel Username11;
    private javax.swing.JLabel Username3;
    private javax.swing.JLabel Username4;
    private javax.swing.JLabel Username5;
    private javax.swing.JLabel Username6;
    private javax.swing.JLabel Username7;
    private javax.swing.JLabel Username8;
    private javax.swing.JLabel Username9;
    private javax.swing.JLabel UsernameIcon2;
    private javax.swing.JLabel UsernameIcon3;
    private javax.swing.JLabel UsernameIcon4;
    private app.bolivia.swing.JCTextField UsernamejCTextField2;
    private app.bolivia.swing.JCTextField UsernamejCTextField3;
    private app.bolivia.swing.JCTextField UsernamejCTextField4;
    private app.bolivia.swing.JCTextField UsernamejCTextField5;
    private javax.swing.JButton jButton15;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private efectos.MaterialShadowCircle materialShadowCircle1;
    // End of variables declaration//GEN-END:variables
}
