/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_management_system;

/**
 *
 * @author PC
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form ReturnBook
     */
    public ReturnBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Username12 = new javax.swing.JLabel();
        Username13 = new javax.swing.JLabel();
        EmailjCTextField7 = new app.bolivia.swing.JCTextField();
        ContactNumberjCTextField8 = new app.bolivia.swing.JCTextField();
        PasswordjCTextField6 = new app.bolivia.swing.JCTextField();
        EmailIcon4 = new javax.swing.JLabel();
        UsernamejCTextField4 = new app.bolivia.swing.JCTextField();
        ContactNumberIcon4 = new javax.swing.JLabel();
        PasswordIcon4 = new javax.swing.JLabel();
        Email4 = new javax.swing.JLabel();
        UsernameIcon4 = new javax.swing.JLabel();
        Password4 = new javax.swing.JLabel();
        ContactNumber4 = new javax.swing.JLabel();
        Username5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Username11 = new javax.swing.JLabel();
        Username10 = new javax.swing.JLabel();
        UsernamejCTextField5 = new app.bolivia.swing.JCTextField();
        UsernameIcon5 = new javax.swing.JLabel();
        PasswordjCTextField7 = new app.bolivia.swing.JCTextField();
        Password5 = new javax.swing.JLabel();
        Username6 = new javax.swing.JLabel();
        EmailIcon2 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(71, 136, 199));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 6, 1080, 50));

        jPanel2.setBackground(new java.awt.Color(71, 136, 199));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(71, 136, 199));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel28.setText("  Home Page");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(15, 15, 15))
        );

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 240, 40));

        jPanel11.setBackground(new java.awt.Color(71, 136, 199));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-books-30 (1).png"))); // NOI18N
        jLabel29.setText("  Manage Books");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(15, 15, 15))
        );

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 40));

        jPanel12.setBackground(new java.awt.Color(71, 136, 199));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-borrow-book-30.png"))); // NOI18N
        jLabel30.setText("  Issue Book");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(15, 15, 15))
        );

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 240, 40));

        jPanel23.setBackground(new java.awt.Color(71, 136, 199));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-students-30.png"))); // NOI18N
        jLabel31.setText("  Manage Students");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(15, 15, 15))
        );

        jPanel2.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, 40));

        jPanel24.setBackground(new java.awt.Color(71, 136, 199));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel32.setText("   Default List");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addGap(15, 15, 15))
        );

        jPanel2.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 240, 40));

        jPanel27.setBackground(new java.awt.Color(71, 136, 199));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-return-book-30.png"))); // NOI18N
        jLabel35.setText("  Return Book");

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel35)
                .addGap(15, 15, 15))
        );

        jPanel2.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, 40));

        jPanel25.setBackground(new java.awt.Color(71, 136, 199));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-course-assign-30.png"))); // NOI18N
        jLabel33.setText("  View Issued Books");

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addGap(15, 15, 15))
        );

        jPanel2.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 240, 40));

        jPanel26.setBackground(new java.awt.Color(71, 136, 199));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-records-30.png"))); // NOI18N
        jLabel34.setText("  View Records");

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addGap(15, 15, 15))
        );

        jPanel2.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, 40));

        jPanel28.setBackground(new java.awt.Color(71, 136, 199));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-logout-30.png"))); // NOI18N
        jLabel36.setText("  Logout");

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel36)
                .addGap(15, 15, 15))
        );

        jPanel2.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 240, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 250, 720));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 2, 2, 2, new java.awt.Color(71, 136, 199)));
        jPanel9.setPreferredSize(new java.awt.Dimension(520, 395));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(71, 136, 199));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-books-50.png"))); // NOI18N
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 16, -1, -1));

        Username12.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Username12.setForeground(new java.awt.Color(71, 136, 199));
        Username12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Username12.setText("Book Details");
        jPanel9.add(Username12, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 22, -1, -1));

        Username13.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Username13.setForeground(new java.awt.Color(71, 136, 199));
        Username13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Username13.setText("|");
        jPanel9.add(Username13, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 16, -1, 42));

        EmailjCTextField7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(71, 136, 199)));
        EmailjCTextField7.setForeground(new java.awt.Color(71, 136, 199));
        EmailjCTextField7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmailjCTextField7.setPhColor(new java.awt.Color(71, 136, 199));
        EmailjCTextField7.setPlaceholder("Author");
        EmailjCTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailjCTextField7ActionPerformed(evt);
            }
        });
        jPanel9.add(EmailjCTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 427, 40));

        ContactNumberjCTextField8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(71, 136, 199)));
        ContactNumberjCTextField8.setForeground(new java.awt.Color(71, 136, 199));
        ContactNumberjCTextField8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ContactNumberjCTextField8.setPhColor(new java.awt.Color(71, 136, 199));
        ContactNumberjCTextField8.setPlaceholder("Quantity");
        ContactNumberjCTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNumberjCTextField8ActionPerformed(evt);
            }
        });
        jPanel9.add(ContactNumberjCTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 427, 40));

        PasswordjCTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(71, 136, 199)));
        PasswordjCTextField6.setForeground(new java.awt.Color(71, 136, 199));
        PasswordjCTextField6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PasswordjCTextField6.setPhColor(new java.awt.Color(71, 136, 199));
        PasswordjCTextField6.setPlaceholder("Book Name");
        PasswordjCTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordjCTextField6ActionPerformed(evt);
            }
        });
        jPanel9.add(PasswordjCTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 427, 40));

        EmailIcon4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EmailIcon4.setForeground(new java.awt.Color(71, 136, 199));
        EmailIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-author-40.png"))); // NOI18N
        jPanel9.add(EmailIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 44));

        UsernamejCTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(71, 136, 199)));
        UsernamejCTextField4.setForeground(new java.awt.Color(71, 136, 199));
        UsernamejCTextField4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UsernamejCTextField4.setPhColor(new java.awt.Color(71, 136, 199));
        UsernamejCTextField4.setPlaceholder("Book ID");
        UsernamejCTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernamejCTextField4ActionPerformed(evt);
            }
        });
        jPanel9.add(UsernamejCTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 427, 40));

        ContactNumberIcon4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ContactNumberIcon4.setForeground(new java.awt.Color(71, 136, 199));
        ContactNumberIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-math-book-40.png"))); // NOI18N
        jPanel9.add(ContactNumberIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, 43));

        PasswordIcon4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PasswordIcon4.setForeground(new java.awt.Color(71, 136, 199));
        PasswordIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-wordbook-40.png"))); // NOI18N
        jPanel9.add(PasswordIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 45));

        Email4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Email4.setForeground(new java.awt.Color(71, 136, 199));
        Email4.setText("Author");
        jPanel9.add(Email4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        UsernameIcon4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        UsernameIcon4.setForeground(new java.awt.Color(71, 136, 199));
        UsernameIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-informatics-book-40.png"))); // NOI18N
        jPanel9.add(UsernameIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 45));

        Password4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Password4.setForeground(new java.awt.Color(71, 136, 199));
        Password4.setText("Book Name");
        jPanel9.add(Password4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        ContactNumber4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ContactNumber4.setForeground(new java.awt.Color(71, 136, 199));
        ContactNumber4.setText("Quantity");
        jPanel9.add(ContactNumber4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        Username5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Username5.setForeground(new java.awt.Color(71, 136, 199));
        Username5.setText("Book ID");
        jPanel9.add(Username5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 508, 660));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 2, 2, 2, new java.awt.Color(71, 136, 199)));
        jPanel8.setPreferredSize(new java.awt.Dimension(520, 395));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(71, 136, 199));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-books-50.png"))); // NOI18N

        Username11.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Username11.setForeground(new java.awt.Color(71, 136, 199));
        Username11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Username11.setText("Return Book");

        Username10.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Username10.setForeground(new java.awt.Color(71, 136, 199));
        Username10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Username10.setText("|");

        UsernamejCTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(71, 136, 199)));
        UsernamejCTextField5.setForeground(new java.awt.Color(71, 136, 199));
        UsernamejCTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UsernamejCTextField5.setPhColor(new java.awt.Color(71, 136, 199));
        UsernamejCTextField5.setPlaceholder("Book ID");
        UsernamejCTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernamejCTextField5ActionPerformed(evt);
            }
        });

        UsernameIcon5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        UsernameIcon5.setForeground(new java.awt.Color(71, 136, 199));
        UsernameIcon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-informatics-book-40.png"))); // NOI18N

        PasswordjCTextField7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(71, 136, 199)));
        PasswordjCTextField7.setForeground(new java.awt.Color(71, 136, 199));
        PasswordjCTextField7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PasswordjCTextField7.setPhColor(new java.awt.Color(71, 136, 199));
        PasswordjCTextField7.setPlaceholder("Book Name");
        PasswordjCTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordjCTextField7ActionPerformed(evt);
            }
        });

        Password5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Password5.setForeground(new java.awt.Color(71, 136, 199));
        Password5.setText("Student ID");

        Username6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Username6.setForeground(new java.awt.Color(71, 136, 199));
        Username6.setText("Book ID");

        EmailIcon2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EmailIcon2.setForeground(new java.awt.Color(71, 136, 199));
        EmailIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-course-40.png"))); // NOI18N

        jButton15.setBackground(new java.awt.Color(71, 136, 199));
        jButton15.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("RETURN BOOK");
        jButton15.setBorder(null);
        jButton15.setFocusPainted(false);

        jButton16.setBackground(new java.awt.Color(71, 136, 199));
        jButton16.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("FIND");
        jButton16.setBorder(null);
        jButton16.setFocusPainted(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Username10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Username11))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(UsernameIcon5)
                                .addGap(10, 10, 10)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UsernamejCTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Username6)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(EmailIcon2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Password5)
                                    .addComponent(PasswordjCTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Username11)
                        .addComponent(Username10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Username6)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernameIcon5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsernamejCTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(58, 58, 58)
                .addComponent(Password5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PasswordjCTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailIcon2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 508, 660));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 1020, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContactNumberjCTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNumberjCTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactNumberjCTextField8ActionPerformed

    private void EmailjCTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailjCTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailjCTextField7ActionPerformed

    private void PasswordjCTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordjCTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordjCTextField6ActionPerformed

    private void UsernamejCTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernamejCTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernamejCTextField4ActionPerformed

    private void PasswordjCTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordjCTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordjCTextField7ActionPerformed

    private void UsernamejCTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernamejCTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernamejCTextField5ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContactNumber4;
    private javax.swing.JLabel ContactNumberIcon4;
    private app.bolivia.swing.JCTextField ContactNumberjCTextField8;
    private javax.swing.JLabel Email4;
    private javax.swing.JLabel EmailIcon2;
    private javax.swing.JLabel EmailIcon4;
    private app.bolivia.swing.JCTextField EmailjCTextField7;
    private javax.swing.JLabel Password4;
    private javax.swing.JLabel Password5;
    private javax.swing.JLabel PasswordIcon4;
    private app.bolivia.swing.JCTextField PasswordjCTextField6;
    private app.bolivia.swing.JCTextField PasswordjCTextField7;
    private javax.swing.JLabel Username10;
    private javax.swing.JLabel Username11;
    private javax.swing.JLabel Username12;
    private javax.swing.JLabel Username13;
    private javax.swing.JLabel Username5;
    private javax.swing.JLabel Username6;
    private javax.swing.JLabel UsernameIcon4;
    private javax.swing.JLabel UsernameIcon5;
    private app.bolivia.swing.JCTextField UsernamejCTextField4;
    private app.bolivia.swing.JCTextField UsernamejCTextField5;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
