/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_management_system;

/**
 *
 * @author Michael James Reluya
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        this.ShowPasswordIcon.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        UsernameIcon = new javax.swing.JLabel();
        UsernamejCTextField = new app.bolivia.swing.JCTextField();
        Password = new javax.swing.JLabel();
        PasswordIcon = new javax.swing.JLabel();
        HidePasswordIcon = new javax.swing.JLabel();
        ShowPasswordIcon = new javax.swing.JLabel();
        PasswordPlaceHolder = new rojerusan.RSPasswordTextPlaceHolder();
        Email = new javax.swing.JLabel();
        EmailIcon = new javax.swing.JLabel();
        EmailjCTextField3 = new app.bolivia.swing.JCTextField();
        ContactNumber = new javax.swing.JLabel();
        ContactNumberIcon = new javax.swing.JLabel();
        ContactNumberjCTextField4 = new app.bolivia.swing.JCTextField();
        SignupButton = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(71, 136, 199));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Library Management System");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/LMS (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel2)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 720));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(71, 136, 199));
        jLabel3.setText("Signup to your account");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 73, -1, -1));

        Username.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(71, 136, 199));
        Username.setText("Username");
        jPanel2.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 141, -1, -1));

        UsernameIcon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        UsernameIcon.setForeground(new java.awt.Color(71, 136, 199));
        UsernameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-male-user-40.png"))); // NOI18N
        jPanel2.add(UsernameIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 168, -1, -1));

        UsernamejCTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(71, 136, 199)));
        UsernamejCTextField.setForeground(new java.awt.Color(71, 136, 199));
        UsernamejCTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        UsernamejCTextField.setPhColor(new java.awt.Color(71, 136, 199));
        UsernamejCTextField.setPlaceholder("juandelacruz");
        UsernamejCTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernamejCTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(UsernamejCTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 168, 289, 40));

        Password.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(71, 136, 199));
        Password.setText("Password");
        jPanel2.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 226, -1, -1));

        PasswordIcon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PasswordIcon.setForeground(new java.awt.Color(71, 136, 199));
        PasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-password-40.png"))); // NOI18N
        jPanel2.add(PasswordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 255, -1, -1));

        HidePasswordIcon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        HidePasswordIcon.setForeground(new java.awt.Color(71, 136, 199));
        HidePasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-invisible-25.png"))); // NOI18N
        HidePasswordIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HidePasswordIconMousePressed(evt);
            }
        });
        jPanel2.add(HidePasswordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, 42));

        ShowPasswordIcon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ShowPasswordIcon.setForeground(new java.awt.Color(71, 136, 199));
        ShowPasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-eye-25.png"))); // NOI18N
        ShowPasswordIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ShowPasswordIconMousePressed(evt);
            }
        });
        jPanel2.add(ShowPasswordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, 42));

        PasswordPlaceHolder.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(71, 136, 199)));
        PasswordPlaceHolder.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PasswordPlaceHolder.setPlaceholder("8+ Password");
        PasswordPlaceHolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordPlaceHolderActionPerformed(evt);
            }
        });
        jPanel2.add(PasswordPlaceHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 253, 289, 42));

        Email.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(71, 136, 199));
        Email.setText("Email");
        jPanel2.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 313, -1, -1));

        EmailIcon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EmailIcon.setForeground(new java.awt.Color(71, 136, 199));
        EmailIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-email-40.png"))); // NOI18N
        jPanel2.add(EmailIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 340, -1, -1));

        EmailjCTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(71, 136, 199)));
        EmailjCTextField3.setForeground(new java.awt.Color(71, 136, 199));
        EmailjCTextField3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        EmailjCTextField3.setPhColor(new java.awt.Color(71, 136, 199));
        EmailjCTextField3.setPlaceholder("juandelacruz@gmail.com");
        EmailjCTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailjCTextField3ActionPerformed(evt);
            }
        });
        jPanel2.add(EmailjCTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 289, 40));

        ContactNumber.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ContactNumber.setForeground(new java.awt.Color(71, 136, 199));
        ContactNumber.setText("Contact Number");
        jPanel2.add(ContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 398, -1, -1));

        ContactNumberIcon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ContactNumberIcon.setForeground(new java.awt.Color(71, 136, 199));
        ContactNumberIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_management_system/icons8-phone-40.png"))); // NOI18N
        jPanel2.add(ContactNumberIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 425, -1, -1));

        ContactNumberjCTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(71, 136, 199)));
        ContactNumberjCTextField4.setForeground(new java.awt.Color(71, 136, 199));
        ContactNumberjCTextField4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ContactNumberjCTextField4.setPhColor(new java.awt.Color(71, 136, 199));
        ContactNumberjCTextField4.setPlaceholder("09123456789");
        ContactNumberjCTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNumberjCTextField4ActionPerformed(evt);
            }
        });
        jPanel2.add(ContactNumberjCTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 425, 289, 40));

        SignupButton.setBackground(new java.awt.Color(71, 136, 199));
        SignupButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        SignupButton.setForeground(new java.awt.Color(255, 255, 255));
        SignupButton.setText("Signup");
        SignupButton.setFocusPainted(false);
        SignupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupButtonActionPerformed(evt);
            }
        });
        jPanel2.add(SignupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 519, 289, 39));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(71, 136, 199));
        jLabel8.setText("OR");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 570, -1, -1));

        LoginButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(71, 136, 199));
        LoginButton.setText("Login");
        LoginButton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(71, 136, 199)));
        LoginButton.setFocusPainted(false);
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 591, 289, 39));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(71, 136, 199));
        jLabel9.setText("I have already an account");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 636, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 500, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void SignupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupButtonActionPerformed
        SignUp SignUpFrame = new SignUp();
        SignUpFrame.setVisible(true);
        SignUpFrame.pack();
        SignUpFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_SignupButtonActionPerformed

    private void UsernamejCTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernamejCTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernamejCTextFieldActionPerformed

    private void EmailjCTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailjCTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailjCTextField3ActionPerformed

    private void ContactNumberjCTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNumberjCTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactNumberjCTextField4ActionPerformed

    private void PasswordPlaceHolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordPlaceHolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordPlaceHolderActionPerformed

    private void HidePasswordIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HidePasswordIconMousePressed
        ShowPasswordIcon.setVisible(true);
        HidePasswordIcon.setVisible(false);
        PasswordPlaceHolder.setEchoChar((char)0);
    }//GEN-LAST:event_HidePasswordIconMousePressed

    private void ShowPasswordIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowPasswordIconMousePressed
        HidePasswordIcon.setVisible(true);
        ShowPasswordIcon.setVisible(false);
        PasswordPlaceHolder.setEchoChar('*');
    }//GEN-LAST:event_ShowPasswordIconMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContactNumber;
    private javax.swing.JLabel ContactNumberIcon;
    private app.bolivia.swing.JCTextField ContactNumberjCTextField4;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel EmailIcon;
    private app.bolivia.swing.JCTextField EmailjCTextField3;
    private javax.swing.JLabel HidePasswordIcon;
    private javax.swing.JToggleButton LoginButton;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel PasswordIcon;
    private rojerusan.RSPasswordTextPlaceHolder PasswordPlaceHolder;
    private javax.swing.JLabel ShowPasswordIcon;
    private javax.swing.JToggleButton SignupButton;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel UsernameIcon;
    private app.bolivia.swing.JCTextField UsernamejCTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
